### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by geoextra** [erming/shout-website#3]
The [Shout demo](http://demo.shout-irc.com/) is currently offline. I could offer free hosting for this :smiley:

**Comment by erming** [comment]
Hey, thanks for reporting.
It was caused by a bug. The bug has been fixed (https://github.com/erming/shout/commit/5e6ac19d0f8b67144af9289813d3f5b9774e28dd), but I hadn't updated the demo server.

It's now live again.
And the hosting I use is pretty fine (EC2 micro), so no worries. But thanks anyway!
